config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  
  resources :items
  
  resources :relationships, only: [:create, :destroy]
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    # delete 'users/sign_out', to: 'devise/sessions#destroy'
  end
  resources :users, only: [:index, :show, :edit, :update]
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end
  #フォローしているかどうかを確認する
  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end
  #指定のユーザのフォローを解除する
  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.guest
   find_or_create_by!(email: 'guest@example.com') do |user|
     user.password = SecureRandom.urlsafe_base64
     # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
   end
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super
    # session[:keep_signed_out] = true
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    # @followings = @user.following
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
     #binding.pry
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "プロフィールを編集しました！"
    else
      render :edit
    end
  end

  def destroy 
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>" class="follow_form">
  <% unless current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.build(followed_id: user.id)) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "＋ フォローする" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |f| %>
      <%= f.submit "フォロー解除" %>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h3>情報を編集する</h3><br>
    <%= form_with(model: @user, local: true) do |f| %>  
      <%= f.label :username %>
      <%= f.text_field :username %><br><br>
      <%= f.label :email %>
      <%= f.email_field :email %><br><br>
      
      <%= f.submit "編集する", class: "btn btn-lg, btn-primary" %>
    <% end %><br><hr>

  <%= link_to 'Myページに戻る', user_path(@user.id) %>

app/views/users/index.html.erb
<div class="row"> 
  <div class="col-3">
    <h2>サイド</h2>
    <div class="list-group"><br>
      <a href="#" class="list-group-item">検索する</a>
      <span class="list-group-item">Search User</span>
      <span class="list-group-item">Search User</span>
    </div>
  </div> 
  
  <div class="col-9">
  <h2>ユーザー一覧</h2><br>
    <% @users.each do |user| %>
      <div class="card w-75 mb-3">
        <div class="card-body">
        <i class="fas fa-user-circle"></i>
          <span>　id: <%= user.id %>｜</span>
          <%= link_to user_path(user.id) do %>
            <%= user.username %>
          <% end %>
          <span>｜<%= user.email %></span>
          <span>｜　　　<%= render 'follow_form', user: user %></span>
        </div>
      </div>
     <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-3">
    <h4>サイドメニュー</h4>
    <div class="list-group"><br>
    <%= link_to new_item_path do %>
      <span class="list-group-item">投稿する</span>
    <% end %>
      <span class="list-group-item">投稿中アイテム</span>
      <span class="list-group-item">売却済み</span>
    </div><br><br><br>

    <h5>探す</h5>
    <div class="list-group">
      <%= link_to items_path do %>
        <span class="list-group-item">みんなの投稿</span>
      <% end %>
      <%= link_to users_path do %>
        <span class="list-group-item">ユーザー一覧</span>
      <% end %>
      <span class="list-group-item">Search</span>
      <span class="list-group-item">Search</span>
    </div><br><br><br>

    <h5>設定</h5>
    <div class="list-group">
      <%= link_to edit_user_path(@user.id) do %>
        <span class="list-group-item">プロフィール編集する</span>
      <% end %>
      <span class="list-group-item">setting</span>
      <span class="list-group-item">setting</span>
    </div><br>
  </div>
  <div class="col-9">
    <div class="jumbotron bg-info">
      <div class="row">
        <div class="col-3">
          <i class="fas fa-user-circle"></i>
        </div>
        <div class="col-9">
          <table class="table w-75">
           <tbody>
             <tr>
               <th>ユーザーid</th>
               <td><%= @user.id %></td>
             </tr>
              <tr>
                <th>ユーザー名</th>
                <td><%= @user.username %></td>
              </tr>
              <tr>
                <th>メールアドレス</th>
                <td><%= @user.email %></td>
              </tr>
              <tr></tr>
            </tbody>
          </table>

        </div>
      </div>
   </div>

    <h3>フォロー中のユーザー</h3><br>
    <% @user.following.each do |user| %>
      <li>
        <%= link_to user_path(user) do %>
          <%= user.username %>
        <% end %>
      /<%= user.email %></li>
    <% end %>
  </div>
</div>